language: java

jdk:
  - oraclejdk8

env:
  global:
    - secure: "GZFAV5a/Y3t7/a/RUkt8LVcFH+kbHrdQ+c+79nvZ9mVqlWXKQlNopJ/c7pagXX4OlqUHLP5RUMGsD4Kfr8VsQUJnB9mIvNWBKPHJWEoHUFQjD8vECZ1O1OA5mvB00TnxHy6HuknzJ1ADyQDuyTCS/c5dZugCKVUVe/7UUSsgF8H2XH+KVM1wDfv6cwCJDt51D/jYPsKLM7DcC6HNCjNBuKe2v5AUeF2//aJDMthpriJK668KbsQNux4pPHOVlcdLJZ9Bxz199LufwZEVDO0jI68LCzDn1BOWUAbB9HiGe/4yGx38eTagQ2v4JAUzBdvT9S45gDIP+Czbs/jgqVKDlUaqiTU3ya/zGi4kWuufu9EkWFP2wZSeyp4h2Wu8zrYcOTdU1ODTn2kSK3JJrMBQZXZI2aMu9WDGt7o7ttFAevkuTzdA6F0m3wb3lEUYJWPPWYM5lZnd+viLk4vbFNBZ79y+DV1Rc2yTQrNcCx3Hxev8RAjX0+aYspP0tC6EEWBphMNBCbmA/qNfcrB0e4ptUAOmq03HZYlqvxsKV/g9Va3ywR4zYbBz2rP4KblN6EAESubXAwhYzKDuuQZgf93FrN1vsl/2PUf3GKTBpaSpkG2llt4q81Cu+MhWiXLLr3eyH5rUK6qWzuUOYraEUdnttqAWt+Z8dZasni0auMAVrrg="
    - secure: "GsX1gQkWp4cLTxOVramCCNwAYdyI1OkOU12UbwzanqH+C+IdwfxwL+kr4n8tTns7dLJY3yYwpgVxbz9o+f30MpYRtj/C4WtyGe7h2NPtR6A0Zjc6oZfusSI8BV5wMHbr62n0006Pp665LLsOneUBw9eR8UnJPiJhwof3ckjp5Ks4jTbMUjvi62XliKvC4jnGskk/VxCYaKrn/OEQl6uw9d8OpIIk6HU7dMN26EffRqt37zPWo8gaUsTNZsU1rWMwuo2J8Fy+4dWqDDrk/TWhYnM1b76gdfgpPFwGznPJyCj0V1lrty2Ip/kjSiusobT3R8WLxiVWoOhC/Y9OYAd6NjXZHTbU0xoA18EbIbQ9TH6u4F4MVEZp1Ihfo2t27ULWJEEM2REm4nYOa+P9Pp5tvoi9G/c7QO+oXeX97x0qUZtF2t06sEsXRdnL+Z8okwz+z9Sie1Xbw1SiEaCms8O2t3i0slB8wxtbA5wRP3IQPvk370/RJ6J4V9c72ugkBRpe8k/sGqh5KwnPAscq3XmkqGniijlg2ZUbBjCgqTH8ieHcBIVCFnWJqUhkPmDw4upjZYVj+DbBAHsNIwtHey/YsICmAUyZCAv3uy8baC/J2PWc7khpXuChP2FyqapGhvCbqAb/LMty7sB7JdWHQ82h4Ro5efNVLLPPo35lTvcOMwk="

  matrix:
    - SQ_VERSION=LTS
    - SQ_VERSION=LATEST_RELEASE

cache:
  directories:
    - '$HOME/.m2/repository'

script: ./travis.sh
